version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '03:00'
      timezone: 'Asia/Shanghai'
    open-pull-requests-limit: 10
    versioning-strategy: increase
    labels:
      - dependencies
    groups:
      bun-workspace-dependencies:
        patterns:
          - '*'
