export interface CaptchaData {
  /** Captcha public ID */
  captcha_id: string
  /** Captcha output token that includes core verification data */
  captcha_output: string
  /** Validation flow number used as a unique identifier */
  lot_number: string
  /** Signed token generated by the captcha service */
  pass_token: string
  /** Captcha generation timestamp (string format) */
  gen_time: string
}

export interface PhoneLoginFormProps {
  /**
   * Send OTP to phone number (with captcha verification data).
   * Typically wraps `authClient.phoneNumber.sendOtp()`.
   */
  sendOtp: (phoneNumber: string, captchaData: CaptchaData) => Promise<void>
  /**
   * Perform phone login with verification code.
   * Returns an object with optional error string.
   */
  login: (
    phoneNumber: string,
    code: string
  ) => Promise<{ error?: string | null }>
  /**
   * Called after successful login (e.g., refresh session + navigate).
   */
  onSuccess: () => void
  /**
   * Optional footer content (e.g., Terms & Privacy).
   */
  footer?: React.ReactNode
}
