/**
 * Parameters required to create a payment QR code URL.
 */
export interface CreateQrCodeUrlParams {
  /** Fixed to 2 decimal places, e.g. "9.90" */
  amount: string
  /** Payment type, e.g. "alipay" or "wxpay" */
  type: string
  /** Unique order ID generated by the application */
  orderId: string
  /** Async notification callback URL */
  notifyUrl: string
  /** Page redirect URL after payment */
  returnUrl: string
}

/**
 * Parameters received in the async notification callback.
 */
export interface NotifyParams {
  sign: string
  sign_type: string
  money?: string
  out_trade_no?: string
  trade_no?: string
  trade_status?: string
  [key: string]: string | number | undefined
}

/**
 * Abstraction over any third-party payment provider.
 * Implement this interface to swap payment channels without touching
 * the core business logic.
 */
export interface PaymentProvider {
  /**
   * Build the redirect / QR-code URL that the user should open to pay.
   */
  createQrCodeUrl(params: CreateQrCodeUrlParams): string

  /**
   * Verify the signature of an async notification callback.
   * Returns `true` when the signature is valid.
   */
  verifyNotify(params: NotifyParams): boolean
}
