export const ICON_SVG_MAP: Record<string, string> = {
  anthropic: '/images/icons/anthropic.svg',
  arcee: '/images/icons/arcee.svg',
  bailian: '/images/icons/bailian.svg',
  baseten: '/images/icons/baseten.svg',
  bedrock: '/images/icons/bedrock.svg',
  bfl: '/images/icons/bfl.svg',
  bytedance: '/images/icons/bytedance.svg',
  cohere: '/images/icons/cohere.svg',
  deepseek: '/images/icons/deepseek.svg',
  fireworks: '/images/icons/fireworks.svg',
  google: '/images/icons/google.svg',
  grok: '/images/icons/grok.svg',
  inception: '/images/icons/inception.svg',
  kimi: '/images/icons/kimi.svg',
  kwaipilot: '/images/icons/kwaipilot.svg',
  longcat: '/images/icons/longcat.svg',
  meta: '/images/icons/meta.svg',
  minimax: '/images/icons/minimax.svg',
  mistral: '/images/icons/mistral.svg',
  moonshot: '/images/icons/moonshot.svg',
  morph: '/images/icons/morph.svg',
  novita: '/images/icons/novita.svg',
  nvidia: '/images/icons/nvidia.svg',
  openai: '/images/icons/openai.svg',
  opencode: '/images/icons/opencode.svg',
  openrouter: '/images/icons/openrouter.svg',
  perplexity: '/images/icons/perplexity.svg',
  'prime-intellect': '/images/icons/prime-intellect.svg',
  qwen: '/images/icons/qwen.svg',
  siliconcloud: '/images/icons/siliconcloud.svg',
  stealth: '/images/icons/stealth.svg',
  vercel: '/images/icons/vercel.svg',
  volcengine: '/images/icons/volcengine.svg',
  voyage: '/images/icons/voyage.svg',
  xai: '/images/icons/xai.svg',
  xiaomimimo: '/images/icons/xiaomimimo.svg',
  zai: '/images/icons/zai.svg',
  zeabur: '/images/icons/zeabur.svg',
} as const

export type IconSvgKey = keyof typeof ICON_SVG_MAP
